baseurl = "http://localhost:1313/"
title = "Forked River Amateur Radio Club"
author = "Gavin Rozzi"
paginate = 10
theme = "BluestNight"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableRobotsTXT = true

[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]
    section = ["HTML", "RSS"]

[Params]
    tagline = "Serving the amateur radio community of Lacey Township, NJ"
    description = "The official website of the Forked River Amateur Radio Club" # Description of your site
    authorbox = true
    author = "Gavin Rozzi"
    post_navigation = false
    thumbnail = "images/thumbnail.png"
    thumbnail_radius = "10%"

#[Params.iubenda]
    #id = ""
    #legal_only = false

#[Params.iubenda.pro]
    #enable_pro = false
    #site_id = ""
    #enable_cookie_policy = false
    #disable_footer_link = true
    #prior_consent = false

[Params.background]
    src = "images/background_lg.jpg"
    medium_src = "images/background_med.png"
    small_src = "images/background_sm.png"
    fit_width = false
    tile = false

[Params.widgets]
    search = false
    recent_articles = true
    categories = true
    tags = false
    tags_counter = false
    patreon = ""

[Params.social]
    gitlab = ""

[Params.piwik]
    enable = true
    # URL to the root of the piwik installation.
    # Can include paths after the TLD (e.g https://example.com/piwik/)
    host = "https://analytics.gavinrozzi.com"
    # ID number of this site. Defaults to 1 if not included
    site_id = 12
    # Include <noscript> tags to track users with javascript disabled
    track_nojs = true
    # Include a link in the site footer to allow users to opt out of analytics
    enable_optout = false


[menu]
  [[menu.main]]
    name = "Alert"
    weight = 1
    parent = "docs-pages"
    identifier = "alert-for-pages"
    url = "docs/site/alert/#page-specific-alerts"
  [[menu.main]]
    name = "Alert"
    weight = 1
    parent = "docs-shortcodes"
    identifier = "alert-shortcode"
    url = "docs/site/alert/#shortcode"
